### ISSUE TITLE
Bilingual transcripts support 

### ISSUE THREAD

**Issue by sachsongngu** [7Ds7/videojs-vjstranscribe#4]
First, Your project is great and still active
Did you ever think about implementation of bilingual transcripts. I am not a coder, so I can't help. But I know it possible, take a look at 
toomva.com
studyphim.vn

**Comment by 7Ds7** [comment]
Thank you for the recommendation.
Although this feature is not planned to be released in the near feature you can always have one translation file containing both languages which will show up on the transcribe area when selected.
