### ISSUE TITLE
Cannot detect videojs.

### ISSUE THREAD

**Issue by biplavsitaula1** [7Ds7/videojs-vjstranscribe#6]
I am having problem while import only. The error says, videojs is not defined. I am using create-react-app and trying to add transcribe to my videojs.
I have imported this way:

```
import videojs from "video.js";
import 'videojs-vjstranscribe'
import "video.js/dist/video-js.css";
```
```
 const player = (playerRef.current = videojs(videoElement, {...options, plugins:{
        vjstranscribe:{}
      }}, () => {
        videojs.log("player is ready");
        onReady && onReady(player);
      }));
```
or
```
 const player = (playerRef.current = videojs(videoElement, options, () => {
        videojs.log("player is ready");
        onReady && onReady(player);
      }));
      
      player?.vjstranscribe()
```
I have tried both ways but cannot do as this plugin cannot detect videojs

`react refresh:6 vjstranscribe videojs not detected`

```
Uncaught ReferenceError: videojs is not defined
    at ./node_modules/videojs-vjstranscribe/src/videojs-vjstranscribe.js (videojs-vjstranscribe.js:11:1)
```

**Comment by 7Ds7** [comment]
Not sure, maybe try and uncomment this line [here](https://github.com/7Ds7/videojs-vjstranscribe/blob/main/src/videojs-vjstranscribe.js#L7) to see if it works for you, or expose the videojs to the global window within your react app
